const URL="https://dvlstwwfjqmsiwktovc.supabase.co";const KEY="sb_publishable_qfiYC_tpn9o1cI0Jp1qRpg_4tFxlU2q";const db=supabase.createClient(URL,KEY);let events=[],cursor=new Date(),view="month";cursor.setDate(1);const $=x=>document.getElementById(x),iso=d=>d.toISOString().slice(0,10),esc=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
async function start(){const {data:{user}}=await db.auth.getUser();if(!user){$("auth").classList.remove("hidden");$("app").classList.add("hidden");return}$("auth").classList.add("hidden");$("app").classList.remove("hidden");$("userEmail").textContent=user.email;load()}
async function load(){const {data,error}=await db.from("events").select("*").order("event_date").order("start_time");if(error)return alert(error.message);events=data||[];render()}
function render(){view==="month"?month():week();upcoming()}
function month(){const f=new Date(cursor.getFullYear(),cursor.getMonth(),1),off=(f.getDay()+6)%7;let h='<div class="weekdays">'+["SEG","TER","QUA","QUI","SEX","SÁB","DOM"].map(x=>`<div>${x}</div>`).join("")+'</div><div class="days">';for(let i=0;i<42;i++){let d=new Date(cursor.getFullYear(),cursor.getMonth(),i-off+1),ds=iso(d),es=events.filter(e=>e.event_date===ds);h+=`<div class="day ${ds===iso(new Date())?"today":""}" data-date="${ds}"><div class="daynum">${d.getDate()}</div>${es.map(e=>`<div class="event" data-id="${e.id}">${e.start_time.slice(0,5)} · ${esc(e.title)}</div>`).join("")}</div>`}$("calendar").innerHTML=h+"</div>";bind()}
function week(){let m=new Date(cursor);m.setDate(m.getDate()-((m.getDay()+6)%7));let h='<div class="weekdays">'+["SEG","TER","QUA","QUI","SEX","SÁB","DOM"].map(x=>`<div>${x}</div>`).join("")+'</div><div class="days">';for(let i=0;i<7;i++){let d=new Date(m);d.setDate(m.getDate()+i),ds=iso(d),es=events.filter(e=>e.event_date===ds);h+=`<div class="day ${ds===iso(new Date())?"today":""}" data-date="${ds}"><div class="daynum">${d.getDate()}/${d.getMonth()+1}</div>${es.map(e=>`<div class="event" data-id="${e.id}">${e.start_time.slice(0,5)} · ${esc(e.title)}</div>`).join("")}</div>`}$("calendar").innerHTML=h+"</div>";bind()}
function bind(){document.querySelectorAll(".day").forEach(x=>x.onclick=e=>{let id=e.target.closest(".event")?.dataset.id;open(id?events.find(a=>a.id===id):null,x.dataset.date)})}
function open(ev,date=iso(new Date())){$("modal").classList.remove("hidden");$("modalTitle").textContent=ev?"Editar compromisso":"Novo compromisso";$("eventId").value=ev?.id||"";$("title").value=ev?.title||"";$("date").value=ev?.event_date||date;$("start").value=(ev?.start_time||"09:00").slice(0,5);$("end").value=(ev?.end_time||"").slice(0,5);$("category").value=ev?.category||"Trabalho";$("reminder").value=ev?.reminder??15;$("repeat").value=ev?.repeat||"none";$("description").value=ev?.description||"";$("deleteBtn").classList.toggle("hidden",!ev)}
async function save(e){e.preventDefault();const {data:{user}}=await db.auth.getUser();const p={user_id:user.id,title:$("title").value,event_date:$("date").value,start_time:$("start").value,end_time:$("end").value||null,category:$("category").value,reminder:+$("reminder").value,repeat:$("repeat").value,description:$("description").value||null};let id=$("eventId").value,r=id?await db.from("events").update(p).eq("id",id):await db.from("events").insert(p);if(r.error)return $("saveMsg").textContent=r.error.message;$("modal").classList.add("hidden");load()}
function upcoming(){$("upcoming").innerHTML=events.slice(0,8).map(e=>`<div class="card"><b>${esc(e.title)}</b><div>${e.event_date} · ${e.start_time.slice(0,5)}</div><small>${esc(e.category)}</small></div>`).join("")||"<p>Nenhum compromisso.</p>"}
$("loginForm").onsubmit=async e=>{e.preventDefault();let r=await db.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(r.error){$("loginMsg").textContent="Erro ao entrar: "+r.error.message}else{ $("loginMsg").textContent="Login realizado!"; start() }};$("logout").onclick=async()=>{await db.auth.signOut();start()};$("addBtn").onclick=()=>open();$("closeModal").onclick=()=>$("modal").classList.add("hidden");$("cancelBtn").onclick=()=>$("modal").classList.add("hidden");$("eventForm").onsubmit=save;$("deleteBtn").onclick=async()=>{if(confirm("Excluir?")){await db.from("events").delete().eq("id",$("eventId").value);$("modal").classList.add("hidden");load()}};$("prevBtn").onclick=()=>{view==="month"?cursor.setMonth(cursor.getMonth()-1):cursor.setDate(cursor.getDate()-7);render()};$("nextBtn").onclick=()=>{view==="month"?cursor.setMonth(cursor.getMonth()+1):cursor.setDate(cursor.getDate()+7);render()};$("todayBtn").onclick=()=>{cursor=new Date();cursor.setDate(1);render()};document.querySelectorAll(".view").forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x===b));render()});start();
