const U="https://dvlstwwfjqmsiwktovc.supabase.co",K="sb_publishable_qfiYC_tpn9o1cI0Jp1qRpg_4tFxlU2q",A=U+"/auth/v1",R=U+"/rest/v1/events",SITE=location.origin;let token=sessionStorage.a||"",user=JSON.parse(sessionStorage.u||"null"),events=[],cursor=new Date(),view="month";cursor.setDate(1);
const $=x=>document.getElementById(x),day=d=>{let x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`},esc=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
async function post(path,b){let r=await fetch(A+path,{method:"POST",headers:{"apikey":K,"Content-Type":"application/json"},body:JSON.stringify(b)}),j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error_description||j.msg||j.message||"HTTP "+r.status);return j}
function show(id){["lf","sf","rf","pf"].forEach(x=>$(x).classList.add("hide"));$(id).classList.remove("hide");$("msg").textContent=""}
async function login(){try{let j=await post("/token?grant_type=password",{email:$("email").value,password:$("pass").value});token=j.access_token;user=j.user;sessionStorage.a=token;sessionStorage.u=JSON.stringify(user);app();load()}catch(e){$("msg").textContent="Erro ao entrar: "+e.message}}
async function signup(){if($("sp").value!==$("sp2").value)return $("msg").textContent="As senhas não conferem.";try{let j=await post("/signup",{email:$("se").value,password:$("sp").value,options:{email_redirect_to:SITE}});if(j.access_token){token=j.access_token;user=j.user;sessionStorage.a=token;sessionStorage.u=JSON.stringify(user);app();load()}else $("msg").textContent="Conta criada. Se a confirmação estiver ativada, confira seu e-mail."}catch(e){$("msg").textContent="Erro ao criar conta: "+e.message}}
async function recover(){try{await post("/recover",{email:$("re").value,redirect_to:SITE+"#reset"});$("msg").textContent="Pedido enviado. Aguarde o e-mail."}catch(e){$("msg").textContent="Erro ao enviar: "+e.message}}
async function password(){if($("np").value!==$("np2").value)return $("msg").textContent="As senhas não conferem.";let r=await fetch(A+"/user",{method:"PUT",headers:{"apikey":K,"Authorization":"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify({password:$("np").value})});let j=await r.json().catch(()=>({}));$("msg").textContent=r.ok?"Senha alterada! Agora volte e entre.":(j.message||j.msg||"Erro ao alterar senha")}
function app(){$("login").classList.add("hide");$("app").classList.remove("hide");$("ue").textContent=user?.email||""}
async function load(){let r=await fetch(R+"?select=*&order=event_date.asc,start_time.asc",{headers:{"apikey":K,"Authorization":"Bearer "+token}});let j=await r.json().catch(()=>[]);if(!r.ok)return $("msg").textContent=j.message||"Erro ao carregar";events=j;render()}
function render(){view==="month"?month():week();$("up").innerHTML=events.slice(0,8).map(e=>`<div class="card"><b>${esc(e.title)}</b><div>${e.event_date} · ${e.start_time.slice(0,5)}</div></div>`).join("")||"<p>Nenhum compromisso.</p>"}
function month(){let f=new Date(cursor.getFullYear(),cursor.getMonth(),1),o=(f.getDay()+6)%7,h='<div class="weekdays">'+["SEG","TER","QUA","QUI","SEX","SÁB","DOM"].map(x=>`<div>${x}</div>`).join("")+'</div><div class="days">';for(let i=0;i<42;i++){let d=new Date(cursor.getFullYear(),cursor.getMonth(),i-o+1),ds=day(d);h+=`<div class="day ${ds===day(new Date())?"today":""}" data-date="${ds}"><b>${d.getDate()}</b>${events.filter(e=>e.event_date===ds).map(e=>`<div class="event" data-id="${e.id}">${e.start_time.slice(0,5)} · ${esc(e.title)}</div>`).join("")}</div>`}$("cal").innerHTML=h+"</div>";bind()}
function week(){let m=new Date(cursor);m.setDate(m.getDate()-((m.getDay()+6)%7));let h='<div class="weekdays">'+["SEG","TER","QUA","QUI","SEX","SÁB","DOM"].map(x=>`<div>${x}</div>`).join("")+'</div><div class="days">';for(let i=0;i<7;i++){let d=new Date(m);d.setDate(m.getDate()+i),ds=day(d);h+=`<div class="day ${ds===day(new Date())?"today":""}" data-date="${ds}"><b>${d.getDate()}/${d.getMonth()+1}</b>${events.filter(e=>e.event_date===ds).map(e=>`<div class="event" data-id="${e.id}">${e.start_time.slice(0,5)} · ${esc(e.title)}</div>`).join("")}</div>`}$("cal").innerHTML=h+"</div>";bind()}
function bind(){document.querySelectorAll(".day").forEach(x=>x.onclick=e=>{let id=e.target.closest(".event")?.dataset.id;open(id?events.find(a=>a.id===id):null,x.dataset.date)})}
function open(e=null,d=day(new Date())){$("modal").classList.remove("hide");$("eid").value=e?.id||"";$("et").value=e?.title||"";$("ed").value=e?.event_date||d;$("es").value=(e?.start_time||"09:00").slice(0,5);$("ee").value=(e?.end_time||"").slice(0,5);$("ec").value=e?.category||"Trabalho";$("er").value=e?.reminder??15;$("ex").value=e?.description||""}
async function save(e){e.preventDefault();let p={user_id:user.id,title:$("et").value,event_date:$("ed").value,start_time:$("es").value,end_time:$("ee").value||null,category:$("ec").value,reminder:+$("er").value,repeat:"none",description:$("ex").value||null},id=$("eid").value,r=await fetch(id?R+"?id=eq."+id:R,{method:id?"PATCH":"POST",headers:{"apikey":K,"Authorization":"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify(p)});if(!r.ok)return $("msg").textContent="Erro ao salvar";$("modal").classList.add("hide");load()}
$("lf").onsubmit=e=>{e.preventDefault();login()};$("sf").onsubmit=e=>{e.preventDefault();signup()};$("rf").onsubmit=e=>{e.preventDefault();recover()};$("pf").onsubmit=e=>{e.preventDefault();password()};$("forgot").onclick=()=>show("rf");$("new").onclick=()=>show("sf");$("back1").onclick=()=>show("lf");$("back2").onclick=()=>show("lf");$("out").onclick=()=>{sessionStorage.clear();location.reload()};$("add").onclick=()=>open();$("close").onclick=()=>$("modal").classList.add("hide");$("ef").onsubmit=save;$("del").onclick=async()=>{let id=$("eid").value;if(id&&confirm("Excluir?")){await fetch(R+"?id=eq."+id,{method:"DELETE",headers:{"apikey":K,"Authorization":"Bearer "+token}});$("modal").classList.add("hide");load()}};$("prev").onclick=()=>{view==="month"?cursor.setMonth(cursor.getMonth()-1):cursor.setDate(cursor.getDate()-7);render()};$("next").onclick=()=>{view==="month"?cursor.setMonth(cursor.getMonth()+1):cursor.setDate(cursor.getDate()+7);render()};$("today").onclick=()=>{cursor=new Date();cursor.setDate(1);render()};document.querySelectorAll(".view").forEach(b=>b.onclick=()=>{view=b.dataset.v;document.querySelectorAll(".view").forEach(x=>x.classList.toggle("active",x===b));render()});
if(location.hash.includes("reset")){let h=new URLSearchParams(location.hash.slice(1));if(h.get("access_token")){token=h.get("access_token");sessionStorage.a=token;show("pf")}else show("lf")}else if(token&&user){app();load()}else show("lf");
